// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddDownload(arg1:string,arg2:string):Promise<string>;

export function CancelJob(arg1:string):Promise<void>;

export function CancelSteamCodePrompt():Promise<void>;

export function CheckSteamCmd():Promise<string>;

export function ForceInstallSteamCmd():Promise<void>;

export function GetConfig():Promise<domain.AppConfig>;

export function GetJobs():Promise<Array<domain.DownloadJob>>;

export function LoginSteam(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:domain.AppConfig):Promise<void>;

export function SubmitSteamCode(arg1:string):Promise<void>;
