// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CancelSteamCodePrompt() {
  return window['go']['main']['App']['CancelSteamCodePrompt']();
}

export function CheckSteamCmd() {
  return window['go']['main']['App']['CheckSteamCmd']();
}

export function ForceInstallSteamCmd() {
  return window['go']['main']['App']['ForceInstallSteamCmd']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function LoginSteam(arg1, arg2) {
  return window['go']['main']['App']['LoginSteam'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SubmitSteamCode(arg1) {
  return window['go']['main']['App']['SubmitSteamCode'](arg1);
}
